stages:
  - build
  - test
  - deploy

image: golang:1.22.5

build:
  stage: build
  script:
  - make build
  artifacts:
    paths:
    - build/
    expire_in: 60 minutes
  only:
  - merge_requests
  - main
  - tags
